import { light, dark, gray, primary, danger, success, warning, red, green, blue, yellow } from './bootstrap.js';

export const colorLight = dark;
export const colorDark = light;
export const bgLight = light;
export const bgDark = dark;
export const borderLight = gray[2];
export const borderDark = gray[6];
export const btnPrimary = primary;
export const btnPrimaryActive = blue[6];
export const btnPrimaryHover = blue[5];
export const btnDisabled = gray[5];
export const btnSuccess = success;
export const btnSuccessActive = green[6];
export const btnSuccessHover = green[5];
export const btnDanger = danger;
export const btnDangerActive = red[6];
export const btnDangerHover = red[5];
export const btnWarning = warning;
export const btnWarningActive = yellow[6];
export const btnWarningHover = yellow[5];
